package:
  name: calcam
  version: {{ GIT_DESCRIBE_TAG }}
 
source:
  path: ../
  git_url: ../

build:
  script: python -m pip install . -vv
  entry_points:
    - calcam = calcam:start_gui

requirements:
  build:
    - git
    - python
  run:
    - python >=3.7
    - matplotlib-base
    - opencv
    - pyqt
    - scipy
    - vtk !=9.1.*,>=7
    - h5py
    - triangle
  run_constrained:
    - libstdcxx-ng >=13
    
about:
  home: http://euratom-software.github.io/calcam/html/index.html
  summary: Spatial calibration tools for science & engineering camera systems (python module + GUI app).
  dev_url: http://github.com/euratom-software/calcam/
  doc_url: http://euratom-software.github.io/calcam/html/index.html
  license: EUPL v1.1
  license_file: LICENSE.txt
  
app:
  entry: calcam
  icon: logo.png
  summary: "The Calcam GUI: spatial calibration tools for science & engineering camera systems."
