name: Publish Releases

on:
  release:
    types: [created]
  
  workflow_dispatch:


jobs:
  update-pypi:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python3 -m pip install --upgrade build
        python3 -m pip install --upgrade twine
    - name: Build distribution
      run: python3 -m build
    - name: Upload to PyPi
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: twine upload dist/*
      
  update-anaconda:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12", "3.11", "3.10"]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Conda environment creation and activation
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ matrix.python-version }}
          environment-file: conda/build_env.yaml
          auto-update-conda: false
          auto-activate-base: false
          show-channel-urls: true
      - name: Build and upload the conda packages
        uses: uibcdf/action-build-and-upload-conda-packages@v1.3.0
        with:
          meta_yaml_dir: conda
          python-version: ${{ matrix.python-version }}
          platform_linux-64: true
          platform_osx-64: true
          platform_win-64: true
          user: calcam
          label: main
          upload: true
          token: ${{ secrets.ANACONDA_TOKEN }}
