name: Publish Releases

on:
  release:
    types: [created]

  workflow_dispatch:


jobs:
  update-pypi:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python3 -m pip install --upgrade build
        python3 -m pip install --upgrade twine
    - name: Build distribution
      run: python3 -m build
    - name: Upload to PyPi
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: twine upload dist/*
      
  update-anaconda:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        pythonVersion: [ 3.6, 3.7, 3.8, 3.9, 3.10, 3.11, 3.12 ]
    steps:
      - uses: actions/checkout@v2
      - name: Anaconda Build and Publish
        uses: fdiblen/anaconda-action@0.1.9
        with:
          channels: 'conda-forge'
          AnacondaToken: ${{ secrets.ANACONDA_TOKEN }}
          publish: true
          publishChannel: calcam
